# Generated by Django 5.1.7 on 2025-04-18 21:59

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='operationallog',
            name='operation',
            field=models.CharField(choices=[('insert', 'Insert'), ('delete', 'Delete'), ('undo', 'Undo'), ('redo', 'Redo'), ('image_insert', 'Image Insert'), ('image_delete', 'Image Delete')], max_length=255),
        ),
        migrations.AlterField(
            model_name='operationallog',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationallog',
            name='updated_content',
            field=models.JSONField(blank=True),
        ),
        migrations.CreateModel(
            name='DocumentAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', multiselectfield.db.fields.MultiSelectField(choices=[('read', 'Read'), ('write', 'Write')], max_length=10)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
        ),
    ]
