# Generated by Django 5.1.7 on 2025-03-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_operationallog_operation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationallog',
            name='operation_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
