# Generated by Django 5.1.7 on 2025-04-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operationallog_operation_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoucumentAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=255)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
        ),
    ]
