# Generated by Django 5.1.7 on 2025-04-01 18:30

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doucumentaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', multiselectfield.db.fields.MultiSelectField(choices=[('read', 'Read'), ('write', 'Write')], max_length=10)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
        ),
        migrations.DeleteModel(
            name='DoucumentAccessToken',
        ),
    ]
