name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Node.js for frontend
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Build frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      # Setup Python for backend
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # create .env file
      - name: Copy .env file
        run: cp .env.example .env

      # Install backend dependencies
      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Prepare backend static files
      - name: Create Static Files
        run: |
          mkdir -p backend/staticfiles
          cp -r frontend/build/* backend/staticfiles/ || echo "No build folder, may be using a different structure"
          cd backend
          python manage.py collectstatic --noinput

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-app-name"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./backend"
