name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Node.js for frontend
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Build frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      # Setup Python for backend
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # create .env file
      - name: Copy .env file
        run: |
          if [ -f ../backend/.env ]; then
            cp ../backend/.env .env
          else
            echo "No ../backend/.env file found, skipping copy."
          fi

      # Load environment variables from .env file
      - name: Load .env file
        run: |
          if [ -f ../backend/.env ]; then
            export $(grep -v '^#' ../backend/.env | xargs)
          else
            echo "No ../backend/.env file found, skipping environment variable loading."
          fi

      # Install backend dependencies
      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create necessary directories and set environment variables
      - name: Setup Backend Environment
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
        run: |
          cd backend
          mkdir -p static
          mkdir -p staticfiles

      # Run database migrations
      - name: Run Database Migrations
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
        run: |
          cd backend
          python manage.py makemigrations
          python manage.py migrate

      # Prepare backend static files
      - name: Create Static Files
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
        run: |
          cd backend
          python manage.py collectstatic --noinput

      # Create admin superuser
      - name: Create Admin Superuser
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
        run: |
          cd backend
          python manage.py create_admin_user

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "text-editor"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./backend"
